# initial params
gpu: 0
seed: 1234
num_classes: 100
image_size: [32, 32, 3]
val_split: 0.2

# training params
batch_size: 128
learning_rate: 0.01
max_lr: 0.01
min_lr: 0.0001
epochs: 200
nesterov: False
monitor: "val_precision"
min_delta: 0
verbose: 1
mode: "max"
patience: 10