# initial params
gpu: 0
seed: 1234
num_classes: 100
image_size: [32, 32, 3]
val_split: 0.1

# training params
batch_size: 128
learning_rate: 0.01
max_lr: 0.01
min_lr: 0.00001
epochs: 200
nesterov: True
monitor: "val_f1"
min_delta: 0
verbose: 1
mode: "max"
patience: 10